- hosts: jenkins
  gather_facts: false
  connection: ssh
  become: true
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    
  - name: Install add-adp repository
    apt: name=software-properties-common state=latest
    
  - name: Add Oracle Java Repository
    apt_repository: repo='ppa:webupd8team/java'
    
  - name: Accept Java 8 License
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
    
  - name: Install Oracle Java 8
    apt: name={{item}} state=latest
    with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
    
  - name: Create Folder
    file:
        path: /home/ubuntu/tomcat
        state: directory
        mode: 0755
        owner: ubuntu
        group: ubuntu
        
  - name: Download Tomcat
    get_url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.27/bin/apache-tomcat-8.0.27.tar.gz dest=/home/ubuntu/tomcat
    
  - name: Extract archive
    unarchive:
	  src: /home/ubuntu/tomcat/apache-tomcat-8.0.27.tar.gz
	  dest: /home/ubuntu/tomcat
	  remote_src: yes
      
  - name: Download Jenkins to tomcat Webapps directory
    get_url: url=http://mirrors.jenkins.io/war-stable/latest/jenkins.war dest=/home/ubuntu/tomcat/apache-tomcat-8.0.27/webapps
      
  - name: start apache-tomcat-8.0.27
    shell: /home/ubuntu/tomcat/apache-tomcat-8.0.27/bin/startup.sh
