version: '2'
services:
    cpdaimler-app:
        image: cpdaimler
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cpdaimler-mysql:3306/cpdaimler?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://cpdaimler-elasticsearch:9200
        ports:
            - 8080:8080
    cpdaimler-mysql:
        extends:
            file: mysql.yml
            service: cpdaimler-mysql
    cpdaimler-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cpdaimler-elasticsearch
