- hosts: ec2-ubuntu
  gather_facts: false
  connection: ssh
  become: true
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    
  - name: Install add-adp repository
    apt: name=software-properties-common state=latest
    
  - name: Add Oracle Java Repository
    apt_repository: repo='ppa:webupd8team/java'
    
  - name: Accept Java 8 License
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
    
  - name: Install Oracle Java 8
    apt: name={{item}} state=latest
    with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
    
  - name: Create Folder
    file:
        path: /home/ubuntu/tomcat
        state: directory
        mode: 0755
        owner: ubuntu
        group: ubuntu
        
  - name: Download Tomcat
    get_url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.27/bin/apache-tomcat-8.0.27.tar.gz dest=/home/ubuntu/tomcat
    
  - name: Extract archive
    unarchive:
	  src: /home/ubuntu/tomcat/apache-tomcat-8.0.27.tar.gz
	  dest: /home/ubuntu/tomcat
	  remote_src: yes
      
  - name: start apache-tomcat-8.0.27
    shell: /home/ubuntu/tomcat/apache-tomcat-8.0.27/bin/startup.sh
  - name: Add Nodesource GPG
    apt_key:
      url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
      id: "68576280"
      state: present

  # Refer: https://github.com/nodesource/distributions#installation-instructions
  - name: Add Nodesource deb repo
    apt_repository:
      # TODO: Remove hardcoded bionic and use ansible global vars instead
      repo: 'deb https://deb.nodesource.com/node_10.x bionic main'
      state: present

  - name: Add Nodesource deb-src repo
    apt_repository:
      repo: 'deb-src https://deb.nodesource.com/node_10.x bionic main'
      state: present

  - name: Install Node.js
    apt:
      pkg:
        - nodejs
      state: present
      update_cache: yes